pipeline {

    agent any

  environment {
       HUB_URL = "http://65.2.186.123:4444/wd/hub"
       BROWSER_NAME = "edge"
       HEADLESS_MODE = "--headless"

   }


    stages {

        stage('Clone Repository') {

            steps {

                git url: 'https://github.com/ajay500ranajava/TutorialNinja.git', branch: 'main'

            }

        }

        stage('Build') {

            steps {

                script {

                    // Clean and build the project

                    sh 'mvn clean compile'

                }

            }

        }

        stage('Run Tests') {

            steps {

                script {

                    // Run Selenium tests using TestNG.xml

                    sh 'mvn test -DsuiteXmlFile=src/test/resources/testng.xml'

                }

            }

        }

    }

    post {

        always {

            // Archive test results

            junit '**/target/surefire-reports/*.xml'

        }

        success {

            echo 'Build and tests executed successfully!'

        }

        failure {

            echo 'Build or tests failed.'

        }

    }

} 