pipeline {

    agent any

    tools {

        // Use the configured Maven and JDK in Jenkins

        maven 'maven3'   // Name as configured in Jenkins

        jdk 'jdk17'      // Name as configured in Jenkins

    }

    stages {

        stage('Clone Repository') {

            steps {

                git url: 'https://github.com/ajay500ranajava/TutorialNinja.git', branch: 'main'

            }

        }

        stage('Build') {

            steps {

                script {

                    sh 'mvn clean compile'

                }

            }

        }

        stage('Run Tests') {

            steps {

                script {

                    sh 'mvn test'

                }

            }

        }

        stage('Publish Test Results') {

            steps {

                junit '**/target/surefire-reports/*.xml'

            }

        }

    }

    post {

        always {

            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true

            junit '**/target/surefire-reports/*.xml'

        }

    }

} 